dataset:
    path: "dataset"
    num_sample: 20
    sample:
        extension: "PNG"

        dim: [256, 256]
        color: "black"

        polygon:
            color: "white"
            dim: [75, 30]